### PR TITLE
migrate to meson

### PR DESCRIPTION
**Pull request by albfan**
- Allow to install
- Add i18n
- Configure test suite
- Add man page
- Parse arguments

### CODE REVIEW

**Comment by vi** [comment]
The pull request looks too big to be just merged as is. It turns a mini-project into not so small project.

> Add i18n

Those translation files look auto-generated and not filled with content. They turn this pull request into a "patchbomb".

---

It is good idea to add meson/cmake, manpage and argument parsing (provided it does not add dependency on `getopt` or something), but probably not by just merging this pull request.

**Comment by albfan** [comment]
Sure. Happy you find it useful.

all po files are generated with gettext. I can remove all the options in LINGUAS and left it empty.

Just let me know which things you find interesting and I can split accordingly. Right now I will split into the metioned list dots, ok?

**Comment by vi** [comment]
> split into the metioned list dots

Good idea. Each one should be a separate pull request. The first one is probably changing project layout / introducing Meson. Other ones should come after the project-layout request is already in.

> I can remove all the options in LINGUAS and left it empty.

Is localisation needed at all for this program? What is to be localized? Manpage or `--help`?

**Comment by vi** [comment]
> Parse arguments

Looks like it:

* removes environment variable-based configuration, making this a breaking change.
* introduces dependency on external library, which may bloaten up the project / hinder portability
* adds some `#include`s which I even don't know how used. Are they all even standard?

**Comment by albfan** [comment]
Got, it will rework all that. I will keep the env vars then. I think those are just a quick way to customize so I turn into options.

Will open different MR, closing this right now.

**Pull request closed without merging**
